---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1vcuxntl9zalxm4lr9wuakxydkw2m3skkpn4x9468yuvgzgvmmvfs6ehjv6"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1vcuxntl9zalxm4lr9wuakxydkw2m3skkpn4x9468yuvgzgvmmvfs6ehjv6"
stores:
  yaml:
    indent: 2
