apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xv88p+yFOBR9VV43/zemhpQ=,iv:OWDhCmOwbg/OSbllAlEoqfJxC2wpZtMyju3XIUeGugY=,tag:iiQ6n0YVawCl0Bc2ApaVjw==,type:str]
sops:
  age:
    - recipient: age1vcuxntl9zalxm4lr9wuakxydkw2m3skkpn4x9468yuvgzgvmmvfs6ehjv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcy9ROFpIajhoZFVvZGMy
        cnF6SSt4OUhCVG5maFpOU2tHK2J1Y0hyYkd3CmdvbmhUZmRnV1ZKVytwdXVuc044
        cmt0Q2lETE9kKzc0Q0FPT3JUdzNRL3MKLS0tIFc5VEdlczVza2FPM1lQMGlyU3FK
        V1ZDajVaWTdhOW5VNVZENVlaV250MFkK8gFJ31Bz+pxsvMz15yyKqTqDklapXGLc
        IQMrNxjxiDjtWOVmob5dphTQlT3Zuebk7bgvwhhu8zSrqTOQ/ee5eQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-25T02:51:58Z"
  mac: ENC[AES256_GCM,data:bCxkqDHWfIDukzUcTfVe5qCZ3xXYPfQKqC91idY6p++j89zIAo0fPxLo69gIEgp40leVFso4Cre1FMF8xyQ6aL+QGnsWoJxF5NhSGykOIYVhZ6heb5fVeL45HQrhxUuMtNBentklu4wxhnKBlPCorHmvDZwaR/wWnEJnfXOVuiw=,iv:LjC2NvqE79ooTiFR1Vl/i0hFQKczCayuY31l3+s4caQ=,tag:tsh41adG6tdHbzLB1qnlkA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
