apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:VAIbcQlgoL64rQ29sGPQdCIfuwUK3pFF4wHQTgBbtgRdUQ2w4qjgwrkANh0kdDn3MQrkxtl8wo520M+hAuBgCGIsnp6+lqOvEqA=,iv:/IP8Gv8UEDDDtUGho/7mdS5il9EFUZJo5Qhicngi+Xs=,tag:BG0QD2o3EUeuqTyHp0ohYA==,type:str]
sops:
  age:
    - recipient: age1vcuxntl9zalxm4lr9wuakxydkw2m3skkpn4x9468yuvgzgvmmvfs6ehjv6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaDd5RmkyZHVBci9uSFd0
        SDdlNnpxUDcyTXVxMGdpc2t6RjhEVkNucmtJClcrY1Vlc20vN3ZXeDVKdkNlMnB4
        MlJTaTJUemR5QXViYUt6WHdKbmhoSFUKLS0tIEtMUnBOQmZkWkEwa3kzYVV4cHJX
        emhueCtndGZMQllqajAzUU44TGlTNHMKL17gc6tcizJLfknv/kv2KD/0tkhFT94N
        7ovgSb7e/w3vYkJYgTOf3Js9BL5jG4JcJ6Iywo/vlUcDjWLONRtriQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-25T12:05:57Z"
  mac: ENC[AES256_GCM,data:R3jAO6nalrJK9/ac/+3W2iUcb6Uo5qt+jlwqhxFNu8A50V7tTLKt02jgSWHsfQ1LxAazU6l/wWjrfUgrCVZ1j3iPAOqm2dTWZl4KgSlMzNupWWPQEwiiuQM/Ndzn8UDQShtpJKH7WtVNAUEmUjzcVWsnKnLo6gWlHA9U2B85fYc=,iv:yuN2cioSjjMW9ah1x5w8A+mdPdjilWkfoN99Ms/ezeM=,tag:SFZK3paVftGU+N2qkqHA3w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
